### ISSUE TITLE
Nefunguje s verzí latte 2.5.1

### ISSUE THREAD

**Issue by rumcais** [contributte/forms-multiplier#40]
Při update latte 2.4.8->2.5.1 hazí chybu 

> Argument 1 passed to Latte\PhpWriter::formatWord() must be of the type string, integer given, called in /home/pavlenda/web/nakatamaranu.cz/public_html/vendor/latte/latte/src/Latte/Compiler/PhpWriter.php on line 83

S verzí 2.4.8 je to OK. M.

**Comment by MartkCz** [comment]
dev version?

**Comment by rumcais** [comment]
v3.0.5 but also tested with the version v3.0.4

**Comment by rumcais** [comment]
My version composer:
`{
	"name": "nette/web-project",
	"description": "Nette: Standard Web Project",
	"keywords": ["nette"],
	"type": "project",
	"license": ["MIT", "BSD-3-Clause", "GPL-2.0", "GPL-3.0"],
	"require": {
		"php": ">=7.1.3",
		"nette/application": "^2.4",
		"nette/bootstrap": "^2.4.2",
		"nette/caching": "^2.5",
		"nette/database": "^2.4",
		"nette/di": "^2.4",
		"nette/finder": "^2.4",
		"nette/forms": "^2.4",
		"nette/http": "^2.4",
		"nette/mail": "^2.4",
		"nette/robot-loader": "^2.4 || ^3.0",
		"nette/security": "^2.4",
		"nette/utils": "^2.4",
		"latte/latte": "^2.4",
		"tracy/tracy": "^2.4",
		"contributte/forms-multiplier": "^3.0"
	},
	"require-dev": {
		"nette/tester": "^2.0"
	},
	"minimum-stability": "stable",
	"config": {
		"platform": {
			"php": "7.1.3"
		}
	}
}`

**Comment by MartkCz** [comment]
Fixed in v3.0.6, but I recommend install dev-master (contributte namespace)
