### ISSUE TITLE
Support for nette/forms ^3.0

### ISSUE THREAD

**Issue by BigOHenry** [contributte/forms-multiplier#41]
After composer update
```
Problem 1
    - contributte/forms-multiplier v3.0.0 requires nette/forms ^2.4 -> satisfiable by nette/forms[v2.4.x-dev].
    - contributte/forms-multiplier v3.0.1 requires nette/forms ^2.4 -> satisfiable by nette/forms[v2.4.x-dev].
    - contributte/forms-multiplier v3.0.2 requires nette/forms ^2.4 -> satisfiable by nette/forms[v2.4.x-dev].
    - contributte/forms-multiplier v3.0.3 requires nette/forms ^2.4 -> satisfiable by nette/forms[v2.4.x-dev].
    - contributte/forms-multiplier v3.0.4 requires nette/forms ^2.4 -> satisfiable by nette/forms[v2.4.x-dev].
    - contributte/forms-multiplier v3.0.6 requires nette/forms ^2.4 -> satisfiable by nette/forms[v2.4.x-dev].
    - contributte/forms-multiplier v3.x-dev requires nette/forms ^2.4 -> satisfiable by nette/forms[v2.4.x-dev].
```

Thank you very much :)

**Comment by BigOHenry** [comment]
![image](https://user-images.githubusercontent.com/15823552/56061265-385bcb80-5d69-11e9-9423-d5c9d8c44729.png)

**Comment by MartkCz** [comment]
Now, you must use contributte/forms-multiplier dev-version

**Comment by BigOHenry** [comment]
True :) Thanks

**Comment by micms** [comment]
I get this error alter update my project to Nette 3.0

![image](https://user-images.githubusercontent.com/48025423/57724066-482d3f00-768a-11e9-8a57-98f0f91b2f28.png)

On clear nette/sandbox is same result...

I have used dev-master, my composer.json:

```
"require": {
	"contributte/forms-multiplier": "dev-master"
},
```

**Comment by MartkCz** [comment]
Fixed

**Comment by BigOHenry** [comment]
`dev-master` is working fine on Nette 3 for me. Cloud you make a new release please? :)

**Comment by f3l1x** [comment]
Just a moment please @BigOHenry. We (@MartkCz) should take a look at documentation and other stuff related to contributte's repository. To finalize it.

**Comment by marten-cz** [comment]
@f3l1x Any update?

**Comment by BigOHenry** [comment]
@f3l1x  Any update on stable release for Nette 3? Thank you

**Comment by BigOHenry** [comment]
Any update on stable release for Nette 3? Thank you

**Comment by BigOHenry** [comment]
Here is quick fix for this error:
vendor/contributte/forms-multiplier/src/Multiplier.php on line 297	
`$resolver = new ComponentResolver($this->httpData, $this->values === null ? [] : $this->values, $this->maxCopies, $this->minCopies);`

**Comment by f3l1x** [comment]
Status update for others. 

https://pehapkari.slack.com/archives/CBD9G0GET/p1594491582246400

![image](https://user-images.githubusercontent.com/538058/88484651-64a45700-cf70-11ea-86b6-a14e415e864d.png)

**Comment by jaroslavlibal** [comment]
I don't know what exact problem had @MartkCz in mind, but adding/removing items seems working for me on the current master (7fb8f41). So maybe the related problem had been already resolved?
