### ISSUE TITLE
MultiplierExtension not found

### ISSUE THREAD

**Issue by JStika** [contributte/forms-multiplier#44]
Hi,

When I use:

extensions:
    - Contributte\FormMultiplier\DI\MultiplierExtension

or 

extensions:
    replicator: Contributte\FormMultiplier\DI\MultiplierExtension

or for older version

extensions:
    - WebChemistry\FormMultiplier\DI\MultiplierExtension

or 

extensions:
    replicator: WebChemistry\FormMultiplier\DI\MultiplierExtension

I got error after install 3.0.6 always (and older version too):
Class 'Contributte\FormMultiplier\DI\MultiplierExtension' not found

Why?
Help, please.

My nette composer:
=============
"require": {
		"php": ">5.6.0",
		"nette/application": "^2.4.4",
		"nette/bootstrap": "^2.4.3",
		"nette/caching": "^2.5",
		"nette/database": "^2.4",
		"nette/di": "^2.4",
		"nette/finder": "^2.4",
		"nette/forms": "^2.4",
		"nette/http": "^2.4",
		"nette/mail": "^2.4",
		"nette/robot-loader": "^2.4.4",
		"nette/safe-stream": "^2.3",
		"nette/security": "^2.4",
		"nette/utils": "^2.4",
		"latte/latte": "^2.4",
		"tracy/tracy": "^2.4",
		"contributte/recaptcha": "^3.1",
		"janmarek/webloader": "dev-master",
		"joseki/webloader-filters": "^1.1",
		"oyejorge/less.php": "v1.7.0.14",
		"leafo/scssphp": "^0.8.2",
		"nextras/mail-panel": "^2.4",
		"matthiasmullie/minify": "^1.3",
		"robmorgan/phinx": "^0.10.7",
		"dg/ftp-deployment": "^2.9",
		"h4kuna/gettext-latte": "dev-master",
		"contributte/application": "^0.3.2",
		"ublaboo/datagrid": "^5.7",
		"o5/grido": "^3.0",
		"ipub/visual-paginator": "@dev",
		"nasext/visual-paginator": "^3.1",
		"contributte/forms-multiplier": "^3.0"
	},
	"require-dev": {
		"nette/tester": "^2.0"
	},
	"minimum-stability": "dev",
	"prefer-stable": true,
	"config": {
		"platform": {
			"php": "7.1"
		}
	}

**Comment by MartkCz** [comment]
dev-master for contributte version (recommended)

DI class:
```Contributte\FormMultiplier\DI\MultiplierExtension``` 

---

^3.0 for webchemistry version

DI class:
`WebChemistry\Forms\Controls\DI\MultiplierExtension`

[source](https://github.com/contributte/forms-multiplier/tree/v3.0.6)
