### ISSUE TITLE
Type error when adding a copy containing another multiplier

### ISSUE THREAD

**Issue by LiborSitek** [contributte/forms-multiplier#53]
Hi, I have found a bug on line https://github.com/contributte/forms-multiplier/blob/master/src/Multiplier.php#L297
When adding a copy with another multiplier, attribute $values contains object ArrayHash instead of array causing TypeError (ComponentResolver requires array as second parameter). This minor change should fix that:
`$resolver = new ComponentResolver($this->httpData, (array) $this->values, $this->maxCopies, $this->minCopies);`

**Comment by f3l1x** [comment]
Hi @LiborSitek, could you test latest dev-master?

**Comment by LiborSitek** [comment]
> Hi @LiborSitek, could you test latest dev-master?

Tested, it seems it works fine now, the bug does not appear any more.
